/* Generated by Yosys 0.59+30 (git sha1 04135ba3e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* hdlname = "fulladder" *)
(* top =  1  *)
(* src = "./fulladder_troj3/fulladder_troj3.v:1.1-44.10" *)
module fulladder(clk, rst, a, b, cin, sum, cout);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output sum;
  wire sum;
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [1:0] _15_;
  wire [1:0] _16_;
  wire [1:0] _17_;
  wire [1:0] _18_;
  wire [1:0] _19_;
  wire a_r;
  wire b_r;
  wire cin_r;
  wire cout_c;
  wire sum_c;
  NOT _20_ (
    .A(_02_),
    .Y(_09_)
  );
  NOR _21_ (
    .A(_00_),
    .B(_01_),
    .Y(_10_)
  );
  NAND _22_ (
    .A(_02_),
    .B(_10_),
    .Y(_11_)
  );
  NAND _23_ (
    .A(_00_),
    .B(_01_),
    .Y(_12_)
  );
  NOT _24_ (
    .A(_12_),
    .Y(_04_)
  );
  NOR _25_ (
    .A(_02_),
    .B(_04_),
    .Y(_05_)
  );
  NOR _26_ (
    .A(_10_),
    .B(_04_),
    .Y(_06_)
  );
  NAND _27_ (
    .A(_09_),
    .B(_06_),
    .Y(_07_)
  );
  NAND _28_ (
    .A(_11_),
    .B(_07_),
    .Y(_13_)
  );
  NOR _29_ (
    .A(_09_),
    .B(_06_),
    .Y(_08_)
  );
  NOR _30_ (
    .A(_05_),
    .B(_08_),
    .Y(_03_)
  );
  DFFSR _31_ (
    .C(clk),
    .D(sum_c),
    .Q(sum),
    .R(rst),
    .S(1'h0)
  );
  DFFSR _32_ (
    .C(clk),
    .D(cout_c),
    .Q(cout),
    .R(rst),
    .S(1'h0)
  );
  DFFSR _33_ (
    .C(clk),
    .D(a),
    .Q(a_r),
    .R(rst),
    .S(1'h0)
  );
  DFFSR _34_ (
    .C(clk),
    .D(b),
    .Q(b_r),
    .R(rst),
    .S(1'h0)
  );
  DFFSR _35_ (
    .C(clk),
    .D(cin),
    .Q(cin_r),
    .R(rst),
    .S(1'h0)
  );
  assign _15_[1] = 1'h0;
  assign _16_[1] = 1'h0;
  assign _18_[1] = _15_[0];
  assign _19_[0] = _18_[0];
  assign _00_ = a_r;
  assign _01_ = b_r;
  assign _02_ = cin_r;
  assign sum_c = _13_;
  assign cout_c = _03_;
endmodule
