/* Generated by Yosys 0.59+30 (git sha1 04135ba3e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* hdlname = "fulladder" *)
(* top =  1  *)
(* src = "./fulladder_troj2/fulladder_troj2.v:1.1-49.10" *)
module fulladder(clk, rst, a, b, cin, sum, cout);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output sum;
  wire sum;
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [1:0] _15_;
  wire [1:0] _16_;
  wire [1:0] _17_;
  wire a_r;
  wire b_r;
  wire cin_r;
  wire cout_c;
  wire sum_c;
  NOT _18_ (
    .A(_05_),
    .Y(_10_)
  );
  NOR _19_ (
    .A(_04_),
    .B(_06_),
    .Y(_11_)
  );
  NOT _20_ (
    .A(_11_),
    .Y(_12_)
  );
  NAND _21_ (
    .A(_05_),
    .B(_12_),
    .Y(_13_)
  );
  NOT _22_ (
    .A(_13_),
    .Y(_02_)
  );
  NAND _23_ (
    .A(_04_),
    .B(_06_),
    .Y(_07_)
  );
  NAND _24_ (
    .A(_10_),
    .B(_11_),
    .Y(_08_)
  );
  NAND _25_ (
    .A(_13_),
    .B(_08_),
    .Y(_09_)
  );
  NAND _26_ (
    .A(_07_),
    .B(_09_),
    .Y(_03_)
  );
  DFFSR _27_ (
    .C(clk),
    .D(_01_),
    .Q(sum),
    .R(rst),
    .S(1'h0)
  );
  DFFSR _28_ (
    .C(clk),
    .D(_00_),
    .Q(cout),
    .R(rst),
    .S(1'h0)
  );
  DFFSR _29_ (
    .C(clk),
    .D(a),
    .Q(a_r),
    .R(rst),
    .S(1'h0)
  );
  DFFSR _30_ (
    .C(clk),
    .D(b),
    .Q(b_r),
    .R(rst),
    .S(1'h0)
  );
  DFFSR _31_ (
    .C(clk),
    .D(cin),
    .Q(cin_r),
    .R(rst),
    .S(1'h0)
  );
  assign _15_[1] = 1'h0;
  assign _16_[1] = 1'h0;
  assign _04_ = a_r;
  assign _05_ = b_r;
  assign _06_ = cin_r;
  assign _00_ = _02_;
  assign _01_ = _03_;
endmodule
